---
title: "Project 4"
author: "Michael Donahue"
date: "May 6, 2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)

arrest_tab <- read_csv("http://www.hcbravo.org/IntroDataSci/misc/BPD_Arrests.csv")
dat <- arrest_tab %>% 
  filter(!is.na(`Location 1`)) %>%
  separate(`Location 1`, c("lat","lng"), sep=",") %>%
  mutate(lat=as.numeric(str_replace(lat, "\\(", ""))) %>%
  mutate(lng=as.numeric(str_replace(lng, "\\)", ""))) %>%
  sample_n(2000)

```



```{r}
library(leaflet)
pal <- colorFactor(c("White", "Black", "Red", "Blue"), domain=c("W", "B", "U", "A"))


dat
balto_map <- leaflet(dat) %>%
  addTiles() %>% 
  addCircleMarkers(
    radius = 1,
    color = ~pal(race),
    fillOpacity = .01) %>%
  addCircleMarkers(
    radius = ~ifelse(age > 65, 10, 0),
    color = "GREEN",
    stroke = FALSE,
    fillOpacity = ~ifelse(age > 65, 1, 0)) %>%
  addCircleMarkers(
    radius = ~ifelse(age < 16, 10, 0),
    color = "YELLOW",
    stroke = FALSE,
    fillOpacity = ~ifelse(age < 16, 1, 0)) %>%
  setView(lat=39.29, lng=-76.61, zoom=11)
balto_map
```
This map includes three sets of marks. A simple one that displays race by dividing it by color, another showcasing old age rage (crimes commited by those 65+) and young crimes (crimes commited by those less than 16).  

